### ISSUE TITLE
How to use your library?

### ISSUE THREAD

**Issue by XFox111** [ionutdanila/ffmpeg.UWP#3]
I've downloaded your library via NuGet but it haven't added any new namespaces. How can I instantiate the player?

**Comment by ionutdanila** [comment]
FFmpeg Libraries are based on native C (unmanaged) code (so they do not add any new usings). They can be referenced in a C++/CX Project (eg. https://github.com/ionutdanila/FFmpegInterop). The FFmpegInterop (which is managed C++) can be used as a reference into a C#/XAML UWP Project. You have a sample in the same repository that shows how to use the MediaStreamSource.

**Comment by XFox111** [comment]
Yes. It did help. Thanks)
