### ISSUE TITLE
Requested Windows Runtime type 'FFmpegInterop.FFmpegInteropMSS' is not registered.

### ISSUE THREAD

**Issue by Boo0317** [ionutdanila/ffmpeg.UWP#5]
I  add  FFmpeg.UWP NuGet Package  and FFmpegInterop.Universal   NuGet Package in my project ,when i build and run the app it throw an exception " Requested Windows Runtime type 'FFmpegInterop.FFmpegInteropMSS' is not registered.", I dont know what happend。。

**Comment by Boo0317** [comment]
I soloved this problem,it seem that I must reference FFmpegInterop project on my project,

**Comment by Code-ScottLe** [comment]
@Boo0317 Can you elaborate more on referencing the FFMpegInterop project? Not quite getting this part :(
